### ISSUE TITLE
`server.port` in application.properties seems to be ignored once `spring-boot-security-starter` has been added into the project.

### ISSUE THREAD

**Issue by zirahvi** [PacktPublishing/Full-Stack-Development-with-Spring-Boot-and-React#4]
This is probably NOT specific to the code in this project/book, but asking anyway just in case some other newbie stumbles on the same issue later on:

When starting with the project I got lot of problems with a lingering java-process that was still bound to port 8080 after I had terminated the application from Eclipse IDE. Thus, I changed `server.port` value in application.properties to `8081` and everything worked fine for long time.

Now that I got to Chapter 5 and added `spring-boot-security-starter` dependency into the project, the `server.port` property seems no longer have any effect: The server now is bound to port `8080`. Is this a bug or a feature of the framework?

**Comment by juhahinkula** [comment]
I have to test that also. I haven't noticed that earlier.

**Comment by Maran9** [comment]
> I have to test that also. I haven't noticed that earlier.

Hi Juha,
Did you get a chance to test this out?

**Comment by juhahinkula** [comment]
Sorry, not yet. Try to test that soon.

**Comment by juhahinkula** [comment]
Hello, I tested to change port with security dependency and there was no any problems. Port was changed successfully.
